### ISSUE TITLE
Regarding to safer bash scripts

### ISSUE THREAD

**Issue by pihentagy** [MechanicalRock/mechanicalrock.github.io#109]
**Piping Carefully**: pipefail may cause some strange side effects, consider:

```bash
slow-command | grep --quiet something
```

When grep exits (on the first match), it will kill slow-command, triggering pipefail.

**Comment by temyers** [comment]
There isn't a reference to an article, so I'm not sure on the action to take here.

If you're looking for ways of handling pipefail, consider:
https://vaneyckt.io/posts/safer_bash_scripts_with_set_euxo_pipefail/

**Comment by pihentagy** [comment]
Ok, what about this one?

https://mywiki.wooledge.org/BashFAQ/105
